// Code generated by Slice Machine. DO NOT EDIT.

import BigNumber from './BigNumber/index.svelte';
import ExternalLink from './ExternalLink/index.svelte';
import FullscreenImage from './FullscreenImage/index.svelte';
import Images from './Images/index.svelte';
import OrderedList from './OrderedList/index.svelte';
import Paragraphs from './Paragraphs/index.svelte';
import Quote from './Quote/index.svelte';
import SectionTitle from './SectionTitle/index.svelte';
import UnorderedList from './UnorderedList/index.svelte';
import Video from './Video/index.svelte';

export const components = {
    big_number: BigNumber,
    external_link: ExternalLink,
    full_width_image: FullscreenImage,
    images: Images,
    ordered_list: OrderedList,
    paragraphs: Paragraphs,
    quote: Quote,
    section_title: SectionTitle,
    unordered_list_item: UnorderedList,
    video: Video,
};
