// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type EducationCaseDocumentDataSlicesSlice =
    | VideoSlice
    | UnorderedListItemSlice
    | SectionTitleSlice
    | QuoteSlice
    | ExternalLinkSlice
    | ImagesSlice
    | ParagraphsSlice
    | OrderedListSlice
    | FullWidthImageSlice
    | BigNumberSlice;

/**
 * Content for odd.studio/education/cases documents
 */
interface EducationCaseDocumentData {
    /**
     * Title field in *odd.studio/education/cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Title for this document. Please avoid long texts.
     * - **API ID Path**: EducationCase.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * Date field in *odd.studio/education/cases*
     *
     * - **Field Type**: Date
     * - **Placeholder**: This date will be used to sort the cases.
     * - **API ID Path**: EducationCase.date
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#date
     */
    date: prismic.DateField;

    /**
     * Is this a priority case? field in *odd.studio/education/cases*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: EducationCase.priority
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    priority: prismic.BooleanField;

    /**
     * Is the page content ready? field in *odd.studio/education/cases*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: EducationCase.ready
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    ready: prismic.BooleanField;

    /**
     * Preview Text field in *odd.studio/education/cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: The text that will be showed on display cards. Please avoid long texts.
     * - **API ID Path**: EducationCase.preview
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    preview: prismic.KeyTextField;

    /**
     * Category field in *odd.studio/education/cases*
     *
     * - **Field Type**: Select
     * - **Placeholder**: Select an option from this drop-down list. Please pay attention to this document's current language.
     * - **Default Value**: -
     * - **API ID Path**: EducationCase.category
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    category: prismic.SelectField<
        '-' | 'Keynote Talk' | 'In-Company',
        'filled'
    >;

    /**
     * Summary field in *odd.studio/education/cases*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A short text that summarizes this case.
     * - **API ID Path**: EducationCase.summary
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    summary: prismic.RichTextField;

    /**
     * Before field in *odd.studio/education/cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Brief description of what the client had before this case.
     * - **API ID Path**: EducationCase.before
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    before: prismic.KeyTextField;

    /**
     * Delivery field in *odd.studio/education/cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Brief description of the main delivery of this case.
     * - **API ID Path**: EducationCase.delivery
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    delivery: prismic.KeyTextField;

    /**
     * Client field in *odd.studio/education/cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Name of the client related to this case.
     * - **API ID Path**: EducationCase.client
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    client: prismic.KeyTextField;

    /**
     * Year field in *odd.studio/education/cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: The year in which the case was completed.
     * - **API ID Path**: EducationCase.year
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    year: prismic.KeyTextField;

    /**
     * Tools field in *odd.studio/education/cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: List of the main tools used in this case.
     * - **API ID Path**: EducationCase.tools
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    tools: prismic.KeyTextField;

    /**
     * Link field in *odd.studio/education/cases*
     *
     * - **Field Type**: Link
     * - **Placeholder**: Link to the case website or to some related content.
     * - **API ID Path**: EducationCase.link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    link: prismic.LinkField;

    /**
     * Display Image field in *odd.studio/education/cases*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: EducationCase.display_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    display_image: prismic.ImageField<never>;

    /**
     * Cover Image field in *odd.studio/education/cases*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: EducationCase.cover_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    cover_image: prismic.ImageField<never>;

    /**
     * Slice Zone field in *odd.studio/education/cases*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: EducationCase.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<EducationCaseDocumentDataSlicesSlice>;
}

/**
 * odd.studio/education/cases document from Prismic
 *
 * - **API ID**: `EducationCase`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EducationCaseDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithUID<
        Simplify<EducationCaseDocumentData>,
        'EducationCase',
        Lang
    >;

type ExperimentsCaseDocumentDataSlicesSlice =
    | VideoSlice
    | QuoteSlice
    | UnorderedListItemSlice
    | SectionTitleSlice
    | ImagesSlice
    | OrderedListSlice
    | ParagraphsSlice
    | ExternalLinkSlice
    | FullWidthImageSlice
    | BigNumberSlice;

/**
 * Content for odd.studio/experiments/cases documents
 */
interface ExperimentsCaseDocumentData {
    /**
     * Title field in *odd.studio/experiments/cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Title for this document. Please avoid long texts.
     * - **API ID Path**: ExperimentsCase.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * Date field in *odd.studio/experiments/cases*
     *
     * - **Field Type**: Date
     * - **Placeholder**: This date will be used to sort the cases.
     * - **API ID Path**: ExperimentsCase.date
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#date
     */
    date: prismic.DateField;

    /**
     * Is this a priority case? field in *odd.studio/experiments/cases*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: ExperimentsCase.priority
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    priority: prismic.BooleanField;

    /**
     * Is the page content ready? field in *odd.studio/experiments/cases*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: ExperimentsCase.ready
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    ready: prismic.BooleanField;

    /**
     * Preview Text field in *odd.studio/experiments/cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: The text that will be showed on display cards. Please avoid long texts.
     * - **API ID Path**: ExperimentsCase.preview
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    preview: prismic.KeyTextField;

    /**
     * Category field in *odd.studio/experiments/cases*
     *
     * - **Field Type**: Select
     * - **Placeholder**: Select an option from this drop-down list. Please pay attention to this document's current language.
     * - **Default Value**: -
     * - **API ID Path**: ExperimentsCase.category
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    category: prismic.SelectField<'-' | '--', 'filled'>;

    /**
     * Summary field in *odd.studio/experiments/cases*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A short text that summarizes this case.
     * - **API ID Path**: ExperimentsCase.summary
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    summary: prismic.RichTextField;

    /**
     * Before field in *odd.studio/experiments/cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Brief description of what the client had before this case.
     * - **API ID Path**: ExperimentsCase.before
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    before: prismic.KeyTextField;

    /**
     * Delivery field in *odd.studio/experiments/cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Brief description of the main delivery of this case.
     * - **API ID Path**: ExperimentsCase.delivery
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    delivery: prismic.KeyTextField;

    /**
     * Client field in *odd.studio/experiments/cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Name of the client related to this case.
     * - **API ID Path**: ExperimentsCase.client
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    client: prismic.KeyTextField;

    /**
     * Year field in *odd.studio/experiments/cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: The year in which the case was completed.
     * - **API ID Path**: ExperimentsCase.year
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    year: prismic.KeyTextField;

    /**
     * Tools field in *odd.studio/experiments/cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: List of the main tools used in this case.
     * - **API ID Path**: ExperimentsCase.tools
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    tools: prismic.KeyTextField;

    /**
     * Link field in *odd.studio/experiments/cases*
     *
     * - **Field Type**: Link
     * - **Placeholder**: Link to the case website or to some related content.
     * - **API ID Path**: ExperimentsCase.link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    link: prismic.LinkField;

    /**
     * Display Image field in *odd.studio/experiments/cases*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: ExperimentsCase.display_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    display_image: prismic.ImageField<never>;

    /**
     * Cover Image field in *odd.studio/experiments/cases*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: ExperimentsCase.cover_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    cover_image: prismic.ImageField<never>;

    /**
     * Slice Zone field in *odd.studio/experiments/cases*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: ExperimentsCase.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<ExperimentsCaseDocumentDataSlicesSlice>;
}

/**
 * odd.studio/experiments/cases document from Prismic
 *
 * - **API ID**: `ExperimentsCase`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ExperimentsCaseDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithUID<
        Simplify<ExperimentsCaseDocumentData>,
        'ExperimentsCase',
        Lang
    >;

type StudioCaseDocumentDataSlicesSlice =
    | UnorderedListItemSlice
    | VideoSlice
    | SectionTitleSlice
    | QuoteSlice
    | FullWidthImageSlice
    | ImagesSlice
    | ParagraphsSlice
    | OrderedListSlice
    | ExternalLinkSlice
    | BigNumberSlice;

/**
 * Content for odd.studio/studio/cases documents
 */
interface StudioCaseDocumentData {
    /**
     * Title field in *odd.studio/studio/cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Title for this document. Please avoid long texts.
     * - **API ID Path**: StudioCase.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * Date field in *odd.studio/studio/cases*
     *
     * - **Field Type**: Date
     * - **Placeholder**: This date will be used to sort the cases.
     * - **API ID Path**: StudioCase.date
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#date
     */
    date: prismic.DateField;

    /**
     * Is this a priority case? field in *odd.studio/studio/cases*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: StudioCase.priority
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    priority: prismic.BooleanField;

    /**
     * Is the page content ready? field in *odd.studio/studio/cases*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: StudioCase.ready
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    ready: prismic.BooleanField;

    /**
     * Preview Text field in *odd.studio/studio/cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: The text that will be showed on display cards. Please avoid long texts.
     * - **API ID Path**: StudioCase.preview
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    preview: prismic.KeyTextField;

    /**
     * Category field in *odd.studio/studio/cases*
     *
     * - **Field Type**: Select
     * - **Placeholder**: Select an option from this drop-down list. Please pay attention to this document's current language.
     * - **Default Value**: -
     * - **API ID Path**: StudioCase.category
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    category: prismic.SelectField<
        | '-'
        | 'Infographics and Reports'
        | 'Storytelling and Microwebsites'
        | 'Dashboards'
        | 'Data-driven Systems',
        'filled'
    >;

    /**
     * Summary field in *odd.studio/studio/cases*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A short text that summarizes this case.
     * - **API ID Path**: StudioCase.summary
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    summary: prismic.RichTextField;

    /**
     * Before field in *odd.studio/studio/cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Brief description of what the client had before this case.
     * - **API ID Path**: StudioCase.before
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    before: prismic.KeyTextField;

    /**
     * Delivery field in *odd.studio/studio/cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Brief description of the main delivery of this case.
     * - **API ID Path**: StudioCase.delivery
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    delivery: prismic.KeyTextField;

    /**
     * Client field in *odd.studio/studio/cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Name of the client related to this case.
     * - **API ID Path**: StudioCase.client
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    client: prismic.KeyTextField;

    /**
     * Year field in *odd.studio/studio/cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: The year in which the case was completed.
     * - **API ID Path**: StudioCase.year
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    year: prismic.KeyTextField;

    /**
     * Tools field in *odd.studio/studio/cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: List of the main tools used in this case.
     * - **API ID Path**: StudioCase.tools
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    tools: prismic.KeyTextField;

    /**
     * Link field in *odd.studio/studio/cases*
     *
     * - **Field Type**: Link
     * - **Placeholder**: Link to the case website or to some related content.
     * - **API ID Path**: StudioCase.link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    link: prismic.LinkField;

    /**
     * Display Image field in *odd.studio/studio/cases*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: StudioCase.display_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    display_image: prismic.ImageField<never>;

    /**
     * Cover Image field in *odd.studio/studio/cases*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: StudioCase.cover_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    cover_image: prismic.ImageField<never>;

    /**
     * Slice Zone field in *odd.studio/studio/cases*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: StudioCase.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<StudioCaseDocumentDataSlicesSlice>;
}

/**
 * odd.studio/studio/cases document from Prismic
 *
 * - **API ID**: `StudioCase`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StudioCaseDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithUID<
        Simplify<StudioCaseDocumentData>,
        'StudioCase',
        Lang
    >;

type OddStudioCasesDocumentDataSlicesSlice =
    | FullWidthImageSlice
    | VideoSlice
    | ImagesSlice
    | ExternalLinkSlice
    | BigNumberSlice
    | QuoteSlice
    | UnorderedListItemSlice
    | OrderedListSlice
    | ParagraphsSlice
    | SectionTitleSlice;

/**
 * Content for Test Cases documents
 */
interface OddStudioCasesDocumentData {
    /**
     * Title field in *Test Cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Title for this document. Please avoid long texts.
     * - **API ID Path**: odd-studio-cases.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * Type of work field in *Test Cases*
     *
     * - **Field Type**: Select
     * - **Placeholder**: Select an option from this drop-down list. Please pay attention to this document's current language.
     * - **API ID Path**: odd-studio-cases.type
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    type: prismic.SelectField<
        | 'Presentations, Reports & Infographics'
        | 'Data Storytelling Micro-websites'
        | 'Interactive Dashboards & Exploratory Solutions'
        | 'Data Design Systems'
        | '-'
        | 'Apresentações, Relatórios & Infográficos'
        | 'Micro-sites de Narrativas de Dados'
        | 'Dashboards Interativos & Soluções Exploratórias'
        | 'Sistemas de Design de Dados'
    >;

    /**
     * Should this document be prioritized on landing pages? field in *Test Cases*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: odd-studio-cases.priority
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    priority: prismic.BooleanField;

    /**
     * Date field in *Test Cases*
     *
     * - **Field Type**: Date
     * - **Placeholder**: This date will be used to sort the cases.
     * - **API ID Path**: odd-studio-cases.date
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#date
     */
    date: prismic.DateField;

    /**
     * Before field in *Test Cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Brief description of what the client had before this case.
     * - **API ID Path**: odd-studio-cases.before
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    before: prismic.KeyTextField;

    /**
     * Delivery field in *Test Cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Brief description of the main delivery of this case.
     * - **API ID Path**: odd-studio-cases.delivery
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    delivery: prismic.KeyTextField;

    /**
     * Client field in *Test Cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Name of the client related to this case.
     * - **API ID Path**: odd-studio-cases.client
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    client: prismic.KeyTextField;

    /**
     * Year field in *Test Cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: The year in which the case was completed.
     * - **API ID Path**: odd-studio-cases.year
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    year: prismic.KeyTextField;

    /**
     * Link field in *Test Cases*
     *
     * - **Field Type**: Link
     * - **Placeholder**: Link to the case website or to some related content.
     * - **API ID Path**: odd-studio-cases.link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    link: prismic.LinkField;

    /**
     * Tools field in *Test Cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: List of the main tools used in this case.
     * - **API ID Path**: odd-studio-cases.tools
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    tools: prismic.KeyTextField;

    /**
     * Summary field in *Test Cases*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A short text that summarizes this case.
     * - **API ID Path**: odd-studio-cases.summary
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    summary: prismic.RichTextField;

    /**
     * Preview Text field in *Test Cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: odd-studio-cases.preview
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    preview: prismic.KeyTextField;

    /**
     * Display Image field in *Test Cases*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: odd-studio-cases.display_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    display_image: prismic.ImageField<never>;

    /**
     * Cover Image field in *Test Cases*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: odd-studio-cases.cover_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    cover_image: prismic.ImageField<never>;

    /**
     * Slice Zone field in *Test Cases*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: odd-studio-cases.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<OddStudioCasesDocumentDataSlicesSlice>;
}

/**
 * Test Cases document from Prismic
 *
 * - **API ID**: `odd-studio-cases`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OddStudioCasesDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithUID<
        Simplify<OddStudioCasesDocumentData>,
        'odd-studio-cases',
        Lang
    >;

/**
 * Primary content in *odd.cases → Slice zone → Section Title → Primary*
 */
export interface OddcasesDocumentDataBodySectionTitleSlicePrimary {
    /**
     * Section Title field in *odd.cases → Slice zone → Section Title → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the text of the section title.
     * - **API ID Path**: oddcases.body[].section_title.primary.section_title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    section_title: prismic.KeyTextField;
}

/**
 * Slice for *odd.cases → Slice zone*
 */
export type OddcasesDocumentDataBodySectionTitleSlice = prismic.Slice<
    'section_title',
    Simplify<OddcasesDocumentDataBodySectionTitleSlicePrimary>,
    never
>;

/**
 * Item content in *odd.cases → Slice zone → Paragraph → Items*
 */
export interface OddcasesDocumentDataBodyParagraphSliceItem {
    /**
     * Paragraph field in *odd.cases → Slice zone → Paragraph → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Insert here the text of the paragraph.
     * - **API ID Path**: oddcases.body[].paragraph.items.paragraph
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    paragraph: prismic.RichTextField;
}

/**
 * Slice for *odd.cases → Slice zone*
 */
export type OddcasesDocumentDataBodyParagraphSlice = prismic.Slice<
    'paragraph',
    Record<string, never>,
    Simplify<OddcasesDocumentDataBodyParagraphSliceItem>
>;

/**
 * Primary content in *odd.cases → Slice zone → Quote → Primary*
 */
export interface OddcasesDocumentDataBodyQuoteSlicePrimary {
    /**
     * Quote Text field in *odd.cases → Slice zone → Quote → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the quote's text.
     * - **API ID Path**: oddcases.body[].quote.primary.quote_text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    quote_text: prismic.KeyTextField;

    /**
     * Quote Author field in *odd.cases → Slice zone → Quote → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the name of the quote's author.
     * - **API ID Path**: oddcases.body[].quote.primary.quote_author
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    quote_author: prismic.KeyTextField;

    /**
     * Quote Author Details field in *odd.cases → Slice zone → Quote → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here more details about the quote's author.
     * - **API ID Path**: oddcases.body[].quote.primary.quote_author_details
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    quote_author_details: prismic.KeyTextField;
}

/**
 * Slice for *odd.cases → Slice zone*
 */
export type OddcasesDocumentDataBodyQuoteSlice = prismic.Slice<
    'quote',
    Simplify<OddcasesDocumentDataBodyQuoteSlicePrimary>,
    never
>;

/**
 * Primary content in *odd.cases → Slice zone → Ordered List → Primary*
 */
export interface OddcasesDocumentDataBodyOrderedListSlicePrimary {
    /**
     * Ordered List field in *odd.cases → Slice zone → Ordered List → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Insert here the items of the ordered list.
     * - **API ID Path**: oddcases.body[].ordered_list.primary.ordered_list
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    ordered_list: prismic.RichTextField;
}

/**
 * Slice for *odd.cases → Slice zone*
 */
export type OddcasesDocumentDataBodyOrderedListSlice = prismic.Slice<
    'ordered_list',
    Simplify<OddcasesDocumentDataBodyOrderedListSlicePrimary>,
    never
>;

/**
 * Primary content in *odd.cases → Slice zone → Unordered List → Primary*
 */
export interface OddcasesDocumentDataBodyUnorderedListSlicePrimary {
    /**
     * Unordered List field in *odd.cases → Slice zone → Unordered List → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Insert here the items of the unordered list.
     * - **API ID Path**: oddcases.body[].unordered_list.primary.unordered_list
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    unordered_list: prismic.RichTextField;
}

/**
 * Slice for *odd.cases → Slice zone*
 */
export type OddcasesDocumentDataBodyUnorderedListSlice = prismic.Slice<
    'unordered_list',
    Simplify<OddcasesDocumentDataBodyUnorderedListSlicePrimary>,
    never
>;

/**
 * Item content in *odd.cases → Slice zone → Big Number → Items*
 */
export interface OddcasesDocumentDataBodyBigNumberSliceItem {
    /**
     * Big Number field in *odd.cases → Slice zone → Big Number → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the big number value.
     * - **API ID Path**: oddcases.body[].big_number.items.big_number
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    big_number: prismic.KeyTextField;

    /**
     * Big Number Text field in *odd.cases → Slice zone → Big Number → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the big number auxiliary text.
     * - **API ID Path**: oddcases.body[].big_number.items.big_number_text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    big_number_text: prismic.KeyTextField;
}

/**
 * Slice for *odd.cases → Slice zone*
 */
export type OddcasesDocumentDataBodyBigNumberSlice = prismic.Slice<
    'big_number',
    Record<string, never>,
    Simplify<OddcasesDocumentDataBodyBigNumberSliceItem>
>;

/**
 * Primary content in *odd.cases → Slice zone → External Link → Primary*
 */
export interface OddcasesDocumentDataBodyExternalLinkSlicePrimary {
    /**
     * External Link Address field in *odd.cases → Slice zone → External Link → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: Insert here the address of the external link.
     * - **API ID Path**: oddcases.body[].external_link.primary.external_link_address
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    external_link_address: prismic.LinkField;

    /**
     * External Link Text field in *odd.cases → Slice zone → External Link → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the text to be rendered as the external link.
     * - **API ID Path**: oddcases.body[].external_link.primary.external_link_text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    external_link_text: prismic.KeyTextField;
}

/**
 * Slice for *odd.cases → Slice zone*
 */
export type OddcasesDocumentDataBodyExternalLinkSlice = prismic.Slice<
    'external_link',
    Simplify<OddcasesDocumentDataBodyExternalLinkSlicePrimary>,
    never
>;

/**
 * Primary content in *odd.cases → Slice zone → Video → Primary*
 */
export interface OddcasesDocumentDataBodyVideoSlicePrimary {
    /**
     * Video Caption field in *odd.cases → Slice zone → Video → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the caption of this video.
     * - **API ID Path**: oddcases.body[].video.primary.video_caption
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    video_caption: prismic.KeyTextField;

    /**
     * Video iFrame HTML field in *odd.cases → Slice zone → Video → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the HTML to create the video iFrame.
     * - **API ID Path**: oddcases.body[].video.primary.video_iframe_html
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    video_iframe_html: prismic.KeyTextField;

    /**
     * Video Origin field in *odd.cases → Slice zone → Video → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: Select the platform where the video is being hosted.
     * - **API ID Path**: oddcases.body[].video.primary.video_origin
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    video_origin: prismic.SelectField<'Vimeo' | 'YouTube'>;
}

/**
 * Slice for *odd.cases → Slice zone*
 */
export type OddcasesDocumentDataBodyVideoSlice = prismic.Slice<
    'video',
    Simplify<OddcasesDocumentDataBodyVideoSlicePrimary>,
    never
>;

/**
 * Primary content in *odd.cases → Slice zone → Image → Primary*
 */
export interface OddcasesDocumentDataBodyImageSlicePrimary {
    /**
     * Image Caption field in *odd.cases → Slice zone → Image → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the caption for the image (or images).
     * - **API ID Path**: oddcases.body[].image.primary.image_caption
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    image_caption: prismic.KeyTextField;
}

/**
 * Item content in *odd.cases → Slice zone → Image → Items*
 */
export interface OddcasesDocumentDataBodyImageSliceItem {
    /**
     * Image Item field in *odd.cases → Slice zone → Image → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: oddcases.body[].image.items.image_item
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    image_item: prismic.ImageField<never>;
}

/**
 * Slice for *odd.cases → Slice zone*
 */
export type OddcasesDocumentDataBodyImageSlice = prismic.Slice<
    'image',
    Simplify<OddcasesDocumentDataBodyImageSlicePrimary>,
    Simplify<OddcasesDocumentDataBodyImageSliceItem>
>;

/**
 * Primary content in *odd.cases → Slice zone → Iframe → Primary*
 */
export interface OddcasesDocumentDataBodyIframeSlicePrimary {
    /**
     * Iframe Title field in *odd.cases → Slice zone → Iframe → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here a title to the iframe.
     * - **API ID Path**: oddcases.body[].iframe.primary.iframe_title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    iframe_title: prismic.KeyTextField;

    /**
     * Iframe Source field in *odd.cases → Slice zone → Iframe → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the link to the iframe source.
     * - **API ID Path**: oddcases.body[].iframe.primary.iframe_source
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    iframe_source: prismic.KeyTextField;
}

/**
 * Slice for *odd.cases → Slice zone*
 */
export type OddcasesDocumentDataBodyIframeSlice = prismic.Slice<
    'iframe',
    Simplify<OddcasesDocumentDataBodyIframeSlicePrimary>,
    never
>;

type OddcasesDocumentDataBodySlice =
    | OddcasesDocumentDataBodySectionTitleSlice
    | OddcasesDocumentDataBodyParagraphSlice
    | OddcasesDocumentDataBodyQuoteSlice
    | OddcasesDocumentDataBodyOrderedListSlice
    | OddcasesDocumentDataBodyUnorderedListSlice
    | OddcasesDocumentDataBodyBigNumberSlice
    | OddcasesDocumentDataBodyExternalLinkSlice
    | OddcasesDocumentDataBodyVideoSlice
    | OddcasesDocumentDataBodyImageSlice
    | OddcasesDocumentDataBodyIframeSlice;

/**
 * Content for odd.cases documents
 */
interface OddcasesDocumentData {
    /**
     * Preview Image field in *odd.cases*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: oddcases.preview_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    preview_image: prismic.ImageField<never>;

    /**
     * Cover Image field in *odd.cases*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: oddcases.cover_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    cover_image: prismic.ImageField<never>;

    /**
     * Title field in *odd.cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here a title for this case.
     * - **API ID Path**: oddcases.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * TL;DR field in *odd.cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here a one-paragraph summary for this case.
     * - **API ID Path**: oddcases.tldr
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    tldr: prismic.KeyTextField;

    /**
     * Client field in *odd.cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the name of the client in this case.
     * - **API ID Path**: oddcases.client
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    client: prismic.KeyTextField;

    /**
     * Type of Work field in *odd.cases*
     *
     * - **Field Type**: Select
     * - **Placeholder**: Select the type of work that is most related to this case. Please pay attention to the current language.
     * - **API ID Path**: oddcases.work_type
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    work_type: prismic.SelectField<
        | 'Data Strategy Design'
        | 'Data Product Prototyping'
        | 'Talks & Applied Education'
        | 'Design de Estratégia de Dados'
        | 'Prototipação de Produtos de Dados'
        | 'Falas e Educação'
        | 'Diseño de Estrategia de Datos'
        | 'Prototipos de Productos de Datos'
        | 'Charlas y Educación'
    >;

    /**
     * Year field in *odd.cases*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here this case's year.
     * - **API ID Path**: oddcases.year
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    year: prismic.KeyTextField;

    /**
     * Strategy Effort Percentage field in *odd.cases*
     *
     * - **Field Type**: Number
     * - **Placeholder**: Insert here the Data Strategy Design effort percentage in this case.
     * - **API ID Path**: oddcases.strategy_effort
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#number
     */
    strategy_effort: prismic.NumberField;

    /**
     * Prototyping Effort Percentage field in *odd.cases*
     *
     * - **Field Type**: Number
     * - **Placeholder**: Insert here the Data Product Prototyping effort percentage in this case.
     * - **API ID Path**: oddcases.prototyping_effort
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#number
     */
    prototyping_effort: prismic.NumberField;

    /**
     * Talks Effort Percentage field in *odd.cases*
     *
     * - **Field Type**: Number
     * - **Placeholder**: Insert here the Talks & Applied Education effort percentage in this case.
     * - **API ID Path**: oddcases.talks_effort
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#number
     */
    talks_effort: prismic.NumberField;

    /**
     * Slice zone field in *odd.cases*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: oddcases.body[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    body: prismic.SliceZone<OddcasesDocumentDataBodySlice>;
}

/**
 * odd.cases document from Prismic
 *
 * - **API ID**: `oddcases`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OddcasesDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithUID<
        Simplify<OddcasesDocumentData>,
        'oddcases',
        Lang
    >;

/**
 * Primary content in *odd.edu → Slice zone → Section Title → Primary*
 */
export interface OddeduDocumentDataBodySectionTitleSlicePrimary {
    /**
     * Section Title field in *odd.edu → Slice zone → Section Title → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the text of the section title.
     * - **API ID Path**: oddedu.body[].section_title.primary.section_title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    section_title: prismic.KeyTextField;
}

/**
 * Slice for *odd.edu → Slice zone*
 */
export type OddeduDocumentDataBodySectionTitleSlice = prismic.Slice<
    'section_title',
    Simplify<OddeduDocumentDataBodySectionTitleSlicePrimary>,
    never
>;

/**
 * Item content in *odd.edu → Slice zone → Paragraph → Items*
 */
export interface OddeduDocumentDataBodyParagraphSliceItem {
    /**
     * Paragraph field in *odd.edu → Slice zone → Paragraph → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Insert here the text of the paragraph.
     * - **API ID Path**: oddedu.body[].paragraph.items.paragraph
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    paragraph: prismic.RichTextField;
}

/**
 * Slice for *odd.edu → Slice zone*
 */
export type OddeduDocumentDataBodyParagraphSlice = prismic.Slice<
    'paragraph',
    Record<string, never>,
    Simplify<OddeduDocumentDataBodyParagraphSliceItem>
>;

/**
 * Primary content in *odd.edu → Slice zone → Quote → Primary*
 */
export interface OddeduDocumentDataBodyQuoteSlicePrimary {
    /**
     * Quote Text field in *odd.edu → Slice zone → Quote → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the quote's text.
     * - **API ID Path**: oddedu.body[].quote.primary.quote_text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    quote_text: prismic.KeyTextField;

    /**
     * Quote Author field in *odd.edu → Slice zone → Quote → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the name of the quote's author.
     * - **API ID Path**: oddedu.body[].quote.primary.quote_author
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    quote_author: prismic.KeyTextField;

    /**
     * Quote Author Details field in *odd.edu → Slice zone → Quote → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here more details about the quote's author.
     * - **API ID Path**: oddedu.body[].quote.primary.quote_author_details
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    quote_author_details: prismic.KeyTextField;
}

/**
 * Slice for *odd.edu → Slice zone*
 */
export type OddeduDocumentDataBodyQuoteSlice = prismic.Slice<
    'quote',
    Simplify<OddeduDocumentDataBodyQuoteSlicePrimary>,
    never
>;

/**
 * Primary content in *odd.edu → Slice zone → Ordered List → Primary*
 */
export interface OddeduDocumentDataBodyOrderedListSlicePrimary {
    /**
     * Ordered List field in *odd.edu → Slice zone → Ordered List → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Insert here the items of the ordered list.
     * - **API ID Path**: oddedu.body[].ordered_list.primary.ordered_list
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    ordered_list: prismic.RichTextField;
}

/**
 * Slice for *odd.edu → Slice zone*
 */
export type OddeduDocumentDataBodyOrderedListSlice = prismic.Slice<
    'ordered_list',
    Simplify<OddeduDocumentDataBodyOrderedListSlicePrimary>,
    never
>;

/**
 * Primary content in *odd.edu → Slice zone → Unordered List → Primary*
 */
export interface OddeduDocumentDataBodyUnorderedListSlicePrimary {
    /**
     * Unordered List field in *odd.edu → Slice zone → Unordered List → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Insert here the items of the unordered list.
     * - **API ID Path**: oddedu.body[].unordered_list.primary.unordered_list
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    unordered_list: prismic.RichTextField;
}

/**
 * Slice for *odd.edu → Slice zone*
 */
export type OddeduDocumentDataBodyUnorderedListSlice = prismic.Slice<
    'unordered_list',
    Simplify<OddeduDocumentDataBodyUnorderedListSlicePrimary>,
    never
>;

/**
 * Item content in *odd.edu → Slice zone → Big Number → Items*
 */
export interface OddeduDocumentDataBodyBigNumberSliceItem {
    /**
     * Big Number field in *odd.edu → Slice zone → Big Number → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the big number value.
     * - **API ID Path**: oddedu.body[].big_number.items.big_number
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    big_number: prismic.KeyTextField;

    /**
     * Big Number Text field in *odd.edu → Slice zone → Big Number → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the big number auxiliary text.
     * - **API ID Path**: oddedu.body[].big_number.items.big_number_text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    big_number_text: prismic.KeyTextField;
}

/**
 * Slice for *odd.edu → Slice zone*
 */
export type OddeduDocumentDataBodyBigNumberSlice = prismic.Slice<
    'big_number',
    Record<string, never>,
    Simplify<OddeduDocumentDataBodyBigNumberSliceItem>
>;

/**
 * Primary content in *odd.edu → Slice zone → External Link → Primary*
 */
export interface OddeduDocumentDataBodyExternalLinkSlicePrimary {
    /**
     * External Link Address field in *odd.edu → Slice zone → External Link → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: Insert here the address of the external link.
     * - **API ID Path**: oddedu.body[].external_link.primary.external_link_address
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    external_link_address: prismic.LinkField;

    /**
     * External Link Text field in *odd.edu → Slice zone → External Link → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the text to be rendered as the external link.
     * - **API ID Path**: oddedu.body[].external_link.primary.external_link_text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    external_link_text: prismic.KeyTextField;
}

/**
 * Slice for *odd.edu → Slice zone*
 */
export type OddeduDocumentDataBodyExternalLinkSlice = prismic.Slice<
    'external_link',
    Simplify<OddeduDocumentDataBodyExternalLinkSlicePrimary>,
    never
>;

/**
 * Primary content in *odd.edu → Slice zone → Video → Primary*
 */
export interface OddeduDocumentDataBodyVideoSlicePrimary {
    /**
     * Video Caption field in *odd.edu → Slice zone → Video → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the caption of this video.
     * - **API ID Path**: oddedu.body[].video.primary.video_caption
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    video_caption: prismic.KeyTextField;

    /**
     * Video iFrame HTML field in *odd.edu → Slice zone → Video → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the HTML to create the video iFrame.
     * - **API ID Path**: oddedu.body[].video.primary.video_iframe_html
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    video_iframe_html: prismic.KeyTextField;

    /**
     * Video Origin field in *odd.edu → Slice zone → Video → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: Select the platform where the video is being hosted.
     * - **API ID Path**: oddedu.body[].video.primary.video_origin
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    video_origin: prismic.SelectField<'Vimeo' | 'YouTube'>;
}

/**
 * Slice for *odd.edu → Slice zone*
 */
export type OddeduDocumentDataBodyVideoSlice = prismic.Slice<
    'video',
    Simplify<OddeduDocumentDataBodyVideoSlicePrimary>,
    never
>;

/**
 * Primary content in *odd.edu → Slice zone → Image → Primary*
 */
export interface OddeduDocumentDataBodyImageSlicePrimary {
    /**
     * Image Caption field in *odd.edu → Slice zone → Image → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the caption for the image (or images).
     * - **API ID Path**: oddedu.body[].image.primary.image_caption
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    image_caption: prismic.KeyTextField;
}

/**
 * Item content in *odd.edu → Slice zone → Image → Items*
 */
export interface OddeduDocumentDataBodyImageSliceItem {
    /**
     * Image Item field in *odd.edu → Slice zone → Image → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: oddedu.body[].image.items.image_item
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    image_item: prismic.ImageField<never>;
}

/**
 * Slice for *odd.edu → Slice zone*
 */
export type OddeduDocumentDataBodyImageSlice = prismic.Slice<
    'image',
    Simplify<OddeduDocumentDataBodyImageSlicePrimary>,
    Simplify<OddeduDocumentDataBodyImageSliceItem>
>;

/**
 * Primary content in *odd.edu → Slice zone → Iframe → Primary*
 */
export interface OddeduDocumentDataBodyIframeSlicePrimary {
    /**
     * Iframe Title field in *odd.edu → Slice zone → Iframe → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here a title to the iframe.
     * - **API ID Path**: oddedu.body[].iframe.primary.iframe_title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    iframe_title: prismic.KeyTextField;

    /**
     * Iframe Source field in *odd.edu → Slice zone → Iframe → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the link to the iframe source.
     * - **API ID Path**: oddedu.body[].iframe.primary.iframe_source
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    iframe_source: prismic.KeyTextField;
}

/**
 * Slice for *odd.edu → Slice zone*
 */
export type OddeduDocumentDataBodyIframeSlice = prismic.Slice<
    'iframe',
    Simplify<OddeduDocumentDataBodyIframeSlicePrimary>,
    never
>;

type OddeduDocumentDataBodySlice =
    | OddeduDocumentDataBodySectionTitleSlice
    | OddeduDocumentDataBodyParagraphSlice
    | OddeduDocumentDataBodyQuoteSlice
    | OddeduDocumentDataBodyOrderedListSlice
    | OddeduDocumentDataBodyUnorderedListSlice
    | OddeduDocumentDataBodyBigNumberSlice
    | OddeduDocumentDataBodyExternalLinkSlice
    | OddeduDocumentDataBodyVideoSlice
    | OddeduDocumentDataBodyImageSlice
    | OddeduDocumentDataBodyIframeSlice;

/**
 * Content for odd.edu documents
 */
interface OddeduDocumentData {
    /**
     * Preview Image field in *odd.edu*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: oddedu.preview_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    preview_image: prismic.ImageField<never>;

    /**
     * Cover Image field in *odd.edu*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: oddedu.cover_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    cover_image: prismic.ImageField<never>;

    /**
     * Name field in *odd.edu*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here a name for this course.
     * - **API ID Path**: oddedu.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    name: prismic.KeyTextField;

    /**
     * Link field in *odd.edu*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here a link for this course.
     * - **API ID Path**: oddedu.link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    link: prismic.KeyTextField;

    /**
     * TL;DR field in *odd.edu*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here a one-paragraph summary for this course.
     * - **API ID Path**: oddedu.tl_dr
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    tl_dr: prismic.KeyTextField;

    /**
     * Slice zone field in *odd.edu*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: oddedu.body[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    body: prismic.SliceZone<OddeduDocumentDataBodySlice>;
}

/**
 * odd.edu document from Prismic
 *
 * - **API ID**: `oddedu`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OddeduDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithUID<
        Simplify<OddeduDocumentData>,
        'oddedu',
        Lang
    >;

/**
 * Primary content in *experiments → Slice zone → Section Title → Primary*
 */
export interface OddexperimentsDocumentDataBodySectionTitleSlicePrimary {
    /**
     * Section Title field in *experiments → Slice zone → Section Title → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the text of the section title.
     * - **API ID Path**: oddexperiments.body[].section_title.primary.section_title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    section_title: prismic.KeyTextField;
}

/**
 * Slice for *experiments → Slice zone*
 */
export type OddexperimentsDocumentDataBodySectionTitleSlice = prismic.Slice<
    'section_title',
    Simplify<OddexperimentsDocumentDataBodySectionTitleSlicePrimary>,
    never
>;

/**
 * Item content in *experiments → Slice zone → Paragraph → Items*
 */
export interface OddexperimentsDocumentDataBodyParagraphSliceItem {
    /**
     * Paragraph field in *experiments → Slice zone → Paragraph → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Insert here the text of the paragraph.
     * - **API ID Path**: oddexperiments.body[].paragraph.items.paragraph
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    paragraph: prismic.RichTextField;
}

/**
 * Slice for *experiments → Slice zone*
 */
export type OddexperimentsDocumentDataBodyParagraphSlice = prismic.Slice<
    'paragraph',
    Record<string, never>,
    Simplify<OddexperimentsDocumentDataBodyParagraphSliceItem>
>;

/**
 * Primary content in *experiments → Slice zone → Quote → Primary*
 */
export interface OddexperimentsDocumentDataBodyQuoteSlicePrimary {
    /**
     * Quote Text field in *experiments → Slice zone → Quote → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the quote's text.
     * - **API ID Path**: oddexperiments.body[].quote.primary.quote_text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    quote_text: prismic.KeyTextField;

    /**
     * Quote Author field in *experiments → Slice zone → Quote → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the name of the quote's author.
     * - **API ID Path**: oddexperiments.body[].quote.primary.quote_author
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    quote_author: prismic.KeyTextField;

    /**
     * Quote Author Details field in *experiments → Slice zone → Quote → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here more details about the quote's author.
     * - **API ID Path**: oddexperiments.body[].quote.primary.quote_author_details
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    quote_author_details: prismic.KeyTextField;
}

/**
 * Slice for *experiments → Slice zone*
 */
export type OddexperimentsDocumentDataBodyQuoteSlice = prismic.Slice<
    'quote',
    Simplify<OddexperimentsDocumentDataBodyQuoteSlicePrimary>,
    never
>;

/**
 * Primary content in *experiments → Slice zone → Ordered List → Primary*
 */
export interface OddexperimentsDocumentDataBodyOrderedListSlicePrimary {
    /**
     * Ordered List field in *experiments → Slice zone → Ordered List → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Insert here the items of the ordered list.
     * - **API ID Path**: oddexperiments.body[].ordered_list.primary.ordered_list
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    ordered_list: prismic.RichTextField;
}

/**
 * Slice for *experiments → Slice zone*
 */
export type OddexperimentsDocumentDataBodyOrderedListSlice = prismic.Slice<
    'ordered_list',
    Simplify<OddexperimentsDocumentDataBodyOrderedListSlicePrimary>,
    never
>;

/**
 * Primary content in *experiments → Slice zone → Unordered List → Primary*
 */
export interface OddexperimentsDocumentDataBodyUnorderedListSlicePrimary {
    /**
     * Unordered List field in *experiments → Slice zone → Unordered List → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Insert here the items of the unordered list.
     * - **API ID Path**: oddexperiments.body[].unordered_list.primary.unordered_list
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    unordered_list: prismic.RichTextField;
}

/**
 * Slice for *experiments → Slice zone*
 */
export type OddexperimentsDocumentDataBodyUnorderedListSlice = prismic.Slice<
    'unordered_list',
    Simplify<OddexperimentsDocumentDataBodyUnorderedListSlicePrimary>,
    never
>;

/**
 * Item content in *experiments → Slice zone → Big Number → Items*
 */
export interface OddexperimentsDocumentDataBodyBigNumberSliceItem {
    /**
     * Big Number field in *experiments → Slice zone → Big Number → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the big number value.
     * - **API ID Path**: oddexperiments.body[].big_number.items.big_number
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    big_number: prismic.KeyTextField;

    /**
     * Big Number Text field in *experiments → Slice zone → Big Number → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the big number auxiliary text.
     * - **API ID Path**: oddexperiments.body[].big_number.items.big_number_text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    big_number_text: prismic.KeyTextField;
}

/**
 * Slice for *experiments → Slice zone*
 */
export type OddexperimentsDocumentDataBodyBigNumberSlice = prismic.Slice<
    'big_number',
    Record<string, never>,
    Simplify<OddexperimentsDocumentDataBodyBigNumberSliceItem>
>;

/**
 * Primary content in *experiments → Slice zone → External Link → Primary*
 */
export interface OddexperimentsDocumentDataBodyExternalLinkSlicePrimary {
    /**
     * External Link Address field in *experiments → Slice zone → External Link → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: Insert here the address of the external link.
     * - **API ID Path**: oddexperiments.body[].external_link.primary.external_link_address
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    external_link_address: prismic.LinkField;

    /**
     * External Link Text field in *experiments → Slice zone → External Link → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the text to be rendered as the external link.
     * - **API ID Path**: oddexperiments.body[].external_link.primary.external_link_text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    external_link_text: prismic.KeyTextField;
}

/**
 * Slice for *experiments → Slice zone*
 */
export type OddexperimentsDocumentDataBodyExternalLinkSlice = prismic.Slice<
    'external_link',
    Simplify<OddexperimentsDocumentDataBodyExternalLinkSlicePrimary>,
    never
>;

/**
 * Primary content in *experiments → Slice zone → Video → Primary*
 */
export interface OddexperimentsDocumentDataBodyVideoSlicePrimary {
    /**
     * Video Caption field in *experiments → Slice zone → Video → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the caption of this video.
     * - **API ID Path**: oddexperiments.body[].video.primary.video_caption
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    video_caption: prismic.KeyTextField;

    /**
     * Video iFrame HTML field in *experiments → Slice zone → Video → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the HTML to create the video iFrame.
     * - **API ID Path**: oddexperiments.body[].video.primary.video_iframe_html
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    video_iframe_html: prismic.KeyTextField;

    /**
     * Video Origin field in *experiments → Slice zone → Video → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: Select the platform where the video is being hosted.
     * - **API ID Path**: oddexperiments.body[].video.primary.video_origin
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    video_origin: prismic.SelectField<'Vimeo' | 'YouTube'>;
}

/**
 * Slice for *experiments → Slice zone*
 */
export type OddexperimentsDocumentDataBodyVideoSlice = prismic.Slice<
    'video',
    Simplify<OddexperimentsDocumentDataBodyVideoSlicePrimary>,
    never
>;

/**
 * Primary content in *experiments → Slice zone → Image → Primary*
 */
export interface OddexperimentsDocumentDataBodyImageSlicePrimary {
    /**
     * Image Caption field in *experiments → Slice zone → Image → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the caption for the image (or images).
     * - **API ID Path**: oddexperiments.body[].image.primary.image_caption
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    image_caption: prismic.KeyTextField;
}

/**
 * Item content in *experiments → Slice zone → Image → Items*
 */
export interface OddexperimentsDocumentDataBodyImageSliceItem {
    /**
     * Image Item field in *experiments → Slice zone → Image → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: oddexperiments.body[].image.items.image_item
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    image_item: prismic.ImageField<never>;
}

/**
 * Slice for *experiments → Slice zone*
 */
export type OddexperimentsDocumentDataBodyImageSlice = prismic.Slice<
    'image',
    Simplify<OddexperimentsDocumentDataBodyImageSlicePrimary>,
    Simplify<OddexperimentsDocumentDataBodyImageSliceItem>
>;

/**
 * Primary content in *experiments → Slice zone → Iframe → Primary*
 */
export interface OddexperimentsDocumentDataBodyIframeSlicePrimary {
    /**
     * Iframe Title field in *experiments → Slice zone → Iframe → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here a title to the iframe.
     * - **API ID Path**: oddexperiments.body[].iframe.primary.iframe_title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    iframe_title: prismic.KeyTextField;

    /**
     * Iframe Source field in *experiments → Slice zone → Iframe → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here the link to the iframe source.
     * - **API ID Path**: oddexperiments.body[].iframe.primary.iframe_source
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    iframe_source: prismic.KeyTextField;
}

/**
 * Slice for *experiments → Slice zone*
 */
export type OddexperimentsDocumentDataBodyIframeSlice = prismic.Slice<
    'iframe',
    Simplify<OddexperimentsDocumentDataBodyIframeSlicePrimary>,
    never
>;

type OddexperimentsDocumentDataBodySlice =
    | OddexperimentsDocumentDataBodySectionTitleSlice
    | OddexperimentsDocumentDataBodyParagraphSlice
    | OddexperimentsDocumentDataBodyQuoteSlice
    | OddexperimentsDocumentDataBodyOrderedListSlice
    | OddexperimentsDocumentDataBodyUnorderedListSlice
    | OddexperimentsDocumentDataBodyBigNumberSlice
    | OddexperimentsDocumentDataBodyExternalLinkSlice
    | OddexperimentsDocumentDataBodyVideoSlice
    | OddexperimentsDocumentDataBodyImageSlice
    | OddexperimentsDocumentDataBodyIframeSlice;

/**
 * Content for experiments documents
 */
interface OddexperimentsDocumentData {
    /**
     * Preview Image field in *experiments*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: oddexperiments.preview_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    preview_image: prismic.ImageField<never>;

    /**
     * Cover Image field in *experiments*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: oddexperiments.cover_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    cover_image: prismic.ImageField<never>;

    /**
     * Title field in *experiments*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Insert here a title for this experiment.
     * - **API ID Path**: oddexperiments.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * Slice zone field in *experiments*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: oddexperiments.body[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    body: prismic.SliceZone<OddexperimentsDocumentDataBodySlice>;
}

/**
 * experiments document from Prismic
 *
 * - **API ID**: `oddexperiments`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OddexperimentsDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithUID<
        Simplify<OddexperimentsDocumentData>,
        'oddexperiments',
        Lang
    >;

export type AllDocumentTypes =
    | EducationCaseDocument
    | ExperimentsCaseDocument
    | StudioCaseDocument
    | OddStudioCasesDocument
    | OddcasesDocument
    | OddeduDocument
    | OddexperimentsDocument;

/**
 * Primary content in *BigNumber → Items*
 */
export interface BigNumberSliceDefaultItem {
    /**
     * Big Number field in *BigNumber → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: The value for this big number.
     * - **API ID Path**: big_number.items[].value
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    value: prismic.KeyTextField;

    /**
     * Big Number Text field in *BigNumber → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: The text for this big number.
     * - **API ID Path**: big_number.items[].text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    text: prismic.KeyTextField;
}

/**
 * Default variation for BigNumber Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BigNumberSliceDefault = prismic.SharedSliceVariation<
    'default',
    Record<string, never>,
    Simplify<BigNumberSliceDefaultItem>
>;

/**
 * Slice variation for *BigNumber*
 */
type BigNumberSliceVariation = BigNumberSliceDefault;

/**
 * BigNumber Shared Slice
 *
 * - **API ID**: `big_number`
 * - **Description**: BigNumber
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BigNumberSlice = prismic.SharedSlice<
    'big_number',
    BigNumberSliceVariation
>;

/**
 * Primary content in *ExternalLink → Primary*
 */
export interface ExternalLinkSliceDefaultPrimary {
    /**
     * External Link Address field in *ExternalLink → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: The address of this external link.
     * - **API ID Path**: external_link.primary.address
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    address: prismic.LinkField;

    /**
     * External Link Text field in *ExternalLink → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: The text of this external link.
     * - **API ID Path**: external_link.primary.text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    text: prismic.KeyTextField;
}

/**
 * Default variation for ExternalLink Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExternalLinkSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<ExternalLinkSliceDefaultPrimary>,
    never
>;

/**
 * Slice variation for *ExternalLink*
 */
type ExternalLinkSliceVariation = ExternalLinkSliceDefault;

/**
 * ExternalLink Shared Slice
 *
 * - **API ID**: `external_link`
 * - **Description**: ExternalLink
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExternalLinkSlice = prismic.SharedSlice<
    'external_link',
    ExternalLinkSliceVariation
>;

/**
 * Primary content in *FullscreenImage → Primary*
 */
export interface FullWidthImageSliceDefaultPrimary {
    /**
     * Image field in *FullscreenImage → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: full_width_image.primary.image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    image: prismic.ImageField<never>;

    /**
     * Images Caption field in *FullscreenImage → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: The caption to show below the image (optional).
     * - **API ID Path**: full_width_image.primary.caption
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    caption: prismic.KeyTextField;
}

/**
 * Default variation for FullscreenImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullWidthImageSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<FullWidthImageSliceDefaultPrimary>,
    never
>;

/**
 * Slice variation for *FullscreenImage*
 */
type FullWidthImageSliceVariation = FullWidthImageSliceDefault;

/**
 * FullscreenImage Shared Slice
 *
 * - **API ID**: `full_width_image`
 * - **Description**: FullWidthImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullWidthImageSlice = prismic.SharedSlice<
    'full_width_image',
    FullWidthImageSliceVariation
>;

/**
 * Primary content in *Images → Primary*
 */
export interface ImagesSliceDefaultPrimary {
    /**
     * Images Caption field in *Images → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: The caption to show below the images (optional).
     * - **API ID Path**: images.primary.caption
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    caption: prismic.KeyTextField;
}

/**
 * Primary content in *Images → Items*
 */
export interface ImagesSliceDefaultItem {
    /**
     * Image field in *Images → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: images.items[].image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    image: prismic.ImageField<never>;
}

/**
 * Default variation for Images Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImagesSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<ImagesSliceDefaultPrimary>,
    Simplify<ImagesSliceDefaultItem>
>;

/**
 * Slice variation for *Images*
 */
type ImagesSliceVariation = ImagesSliceDefault;

/**
 * Images Shared Slice
 *
 * - **API ID**: `images`
 * - **Description**: Images
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImagesSlice = prismic.SharedSlice<'images', ImagesSliceVariation>;

/**
 * Primary content in *OrderedList → Primary*
 */
export interface OrderedListSliceDefaultPrimary {
    /**
     * title field in *OrderedList → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: The text for the title of this list (optional).
     * - **API ID Path**: ordered_list.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;
}

/**
 * Primary content in *OrderedList → Items*
 */
export interface OrderedListSliceDefaultItem {
    /**
     * Ordered List Item field in *OrderedList → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: The text of one of the list items. You can use bold, italic and links here.
     * - **API ID Path**: ordered_list.items[].item
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    item: prismic.RichTextField;
}

/**
 * Default variation for OrderedList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OrderedListSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<OrderedListSliceDefaultPrimary>,
    Simplify<OrderedListSliceDefaultItem>
>;

/**
 * Slice variation for *OrderedList*
 */
type OrderedListSliceVariation = OrderedListSliceDefault;

/**
 * OrderedList Shared Slice
 *
 * - **API ID**: `ordered_list`
 * - **Description**: OrderedList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OrderedListSlice = prismic.SharedSlice<
    'ordered_list',
    OrderedListSliceVariation
>;

/**
 * Primary content in *Paragraphs → Items*
 */
export interface ParagraphsSliceDefaultItem {
    /**
     * Paragraph field in *Paragraphs → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: The text of this paragraph. You can use bold, italic and links here.
     * - **API ID Path**: paragraphs.items[].paragraph
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    paragraph: prismic.RichTextField;
}

/**
 * Default variation for Paragraphs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ParagraphsSliceDefault = prismic.SharedSliceVariation<
    'default',
    Record<string, never>,
    Simplify<ParagraphsSliceDefaultItem>
>;

/**
 * Slice variation for *Paragraphs*
 */
type ParagraphsSliceVariation = ParagraphsSliceDefault;

/**
 * Paragraphs Shared Slice
 *
 * - **API ID**: `paragraphs`
 * - **Description**: Paragraphs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ParagraphsSlice = prismic.SharedSlice<
    'paragraphs',
    ParagraphsSliceVariation
>;

/**
 * Primary content in *Quote → Primary*
 */
export interface QuoteSliceDefaultPrimary {
    /**
     * Text field in *Quote → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: The text of this quote. Don't include quotation marks!
     * - **API ID Path**: quote.primary.text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    text: prismic.KeyTextField;

    /**
     * Author field in *Quote → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: The name of this quote's author.
     * - **API ID Path**: quote.primary.author
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    author: prismic.KeyTextField;

    /**
     * Details field in *Quote → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Brief description of this quote's author (optional).
     * - **API ID Path**: quote.primary.details
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    details: prismic.KeyTextField;
}

/**
 * Default variation for Quote Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<QuoteSliceDefaultPrimary>,
    never
>;

/**
 * Slice variation for *Quote*
 */
type QuoteSliceVariation = QuoteSliceDefault;

/**
 * Quote Shared Slice
 *
 * - **API ID**: `quote`
 * - **Description**: Quote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteSlice = prismic.SharedSlice<'quote', QuoteSliceVariation>;

/**
 * Primary content in *SectionTitle → Primary*
 */
export interface SectionTitleSliceDefaultPrimary {
    /**
     * Text field in *SectionTitle → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: The text of this section title.
     * - **API ID Path**: section_title.primary.text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    text: prismic.KeyTextField;
}

/**
 * Default variation for SectionTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionTitleSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<SectionTitleSliceDefaultPrimary>,
    never
>;

/**
 * Slice variation for *SectionTitle*
 */
type SectionTitleSliceVariation = SectionTitleSliceDefault;

/**
 * SectionTitle Shared Slice
 *
 * - **API ID**: `section_title`
 * - **Description**: SectionTitle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionTitleSlice = prismic.SharedSlice<
    'section_title',
    SectionTitleSliceVariation
>;

/**
 * Primary content in *UnorderedList → Primary*
 */
export interface UnorderedListItemSliceDefaultPrimary {
    /**
     * title field in *UnorderedList → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: The text for the title of this list (optional).
     * - **API ID Path**: unordered_list_item.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;
}

/**
 * Primary content in *UnorderedList → Items*
 */
export interface UnorderedListItemSliceDefaultItem {
    /**
     * Unordered List Item field in *UnorderedList → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: The text of one of the list items. You can use bold, italic and links here.
     * - **API ID Path**: unordered_list_item.items[].item
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    item: prismic.RichTextField;
}

/**
 * Default variation for UnorderedList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type UnorderedListItemSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<UnorderedListItemSliceDefaultPrimary>,
    Simplify<UnorderedListItemSliceDefaultItem>
>;

/**
 * Slice variation for *UnorderedList*
 */
type UnorderedListItemSliceVariation = UnorderedListItemSliceDefault;

/**
 * UnorderedList Shared Slice
 *
 * - **API ID**: `unordered_list_item`
 * - **Description**: UnorderedListItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type UnorderedListItemSlice = prismic.SharedSlice<
    'unordered_list_item',
    UnorderedListItemSliceVariation
>;

/**
 * Primary content in *Video → Primary*
 */
export interface VideoSliceDefaultPrimary {
    /**
     * Video iFrame field in *Video → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: The iframe snippet of this video.
     * - **API ID Path**: video.primary.iframe
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    iframe: prismic.KeyTextField;

    /**
     * Video Caption field in *Video → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: The caption of this video (optional).
     * - **API ID Path**: video.primary.caption
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    caption: prismic.KeyTextField;
}

/**
 * Default variation for Video Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<VideoSliceDefaultPrimary>,
    never
>;

/**
 * Slice variation for *Video*
 */
type VideoSliceVariation = VideoSliceDefault;

/**
 * Video Shared Slice
 *
 * - **API ID**: `video`
 * - **Description**: Video
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoSlice = prismic.SharedSlice<'video', VideoSliceVariation>;

declare module '@prismicio/client' {
    interface CreateClient {
        (
            repositoryNameOrEndpoint: string,
            options?: prismic.ClientConfig
        ): prismic.Client<AllDocumentTypes>;
    }

    namespace Content {
        export type {
            EducationCaseDocument,
            EducationCaseDocumentData,
            EducationCaseDocumentDataSlicesSlice,
            ExperimentsCaseDocument,
            ExperimentsCaseDocumentData,
            ExperimentsCaseDocumentDataSlicesSlice,
            StudioCaseDocument,
            StudioCaseDocumentData,
            StudioCaseDocumentDataSlicesSlice,
            OddStudioCasesDocument,
            OddStudioCasesDocumentData,
            OddStudioCasesDocumentDataSlicesSlice,
            OddcasesDocument,
            OddcasesDocumentData,
            OddcasesDocumentDataBodySectionTitleSlicePrimary,
            OddcasesDocumentDataBodyParagraphSliceItem,
            OddcasesDocumentDataBodyQuoteSlicePrimary,
            OddcasesDocumentDataBodyOrderedListSlicePrimary,
            OddcasesDocumentDataBodyUnorderedListSlicePrimary,
            OddcasesDocumentDataBodyBigNumberSliceItem,
            OddcasesDocumentDataBodyExternalLinkSlicePrimary,
            OddcasesDocumentDataBodyVideoSlicePrimary,
            OddcasesDocumentDataBodyImageSlicePrimary,
            OddcasesDocumentDataBodyImageSliceItem,
            OddcasesDocumentDataBodyIframeSlicePrimary,
            OddcasesDocumentDataBodySlice,
            OddeduDocument,
            OddeduDocumentData,
            OddeduDocumentDataBodySectionTitleSlicePrimary,
            OddeduDocumentDataBodyParagraphSliceItem,
            OddeduDocumentDataBodyQuoteSlicePrimary,
            OddeduDocumentDataBodyOrderedListSlicePrimary,
            OddeduDocumentDataBodyUnorderedListSlicePrimary,
            OddeduDocumentDataBodyBigNumberSliceItem,
            OddeduDocumentDataBodyExternalLinkSlicePrimary,
            OddeduDocumentDataBodyVideoSlicePrimary,
            OddeduDocumentDataBodyImageSlicePrimary,
            OddeduDocumentDataBodyImageSliceItem,
            OddeduDocumentDataBodyIframeSlicePrimary,
            OddeduDocumentDataBodySlice,
            OddexperimentsDocument,
            OddexperimentsDocumentData,
            OddexperimentsDocumentDataBodySectionTitleSlicePrimary,
            OddexperimentsDocumentDataBodyParagraphSliceItem,
            OddexperimentsDocumentDataBodyQuoteSlicePrimary,
            OddexperimentsDocumentDataBodyOrderedListSlicePrimary,
            OddexperimentsDocumentDataBodyUnorderedListSlicePrimary,
            OddexperimentsDocumentDataBodyBigNumberSliceItem,
            OddexperimentsDocumentDataBodyExternalLinkSlicePrimary,
            OddexperimentsDocumentDataBodyVideoSlicePrimary,
            OddexperimentsDocumentDataBodyImageSlicePrimary,
            OddexperimentsDocumentDataBodyImageSliceItem,
            OddexperimentsDocumentDataBodyIframeSlicePrimary,
            OddexperimentsDocumentDataBodySlice,
            AllDocumentTypes,
            BigNumberSlice,
            BigNumberSliceDefaultItem,
            BigNumberSliceVariation,
            BigNumberSliceDefault,
            ExternalLinkSlice,
            ExternalLinkSliceDefaultPrimary,
            ExternalLinkSliceVariation,
            ExternalLinkSliceDefault,
            FullWidthImageSlice,
            FullWidthImageSliceDefaultPrimary,
            FullWidthImageSliceVariation,
            FullWidthImageSliceDefault,
            ImagesSlice,
            ImagesSliceDefaultPrimary,
            ImagesSliceDefaultItem,
            ImagesSliceVariation,
            ImagesSliceDefault,
            OrderedListSlice,
            OrderedListSliceDefaultPrimary,
            OrderedListSliceDefaultItem,
            OrderedListSliceVariation,
            OrderedListSliceDefault,
            ParagraphsSlice,
            ParagraphsSliceDefaultItem,
            ParagraphsSliceVariation,
            ParagraphsSliceDefault,
            QuoteSlice,
            QuoteSliceDefaultPrimary,
            QuoteSliceVariation,
            QuoteSliceDefault,
            SectionTitleSlice,
            SectionTitleSliceDefaultPrimary,
            SectionTitleSliceVariation,
            SectionTitleSliceDefault,
            UnorderedListItemSlice,
            UnorderedListItemSliceDefaultPrimary,
            UnorderedListItemSliceDefaultItem,
            UnorderedListItemSliceVariation,
            UnorderedListItemSliceDefault,
            VideoSlice,
            VideoSliceDefaultPrimary,
            VideoSliceVariation,
            VideoSliceDefault,
        };
    }
}
